"""Create all tables

Revision ID: ca3852ccd27e
Revises: 
Create Date: 2025-12-26 16:18:50.222741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca3852ccd27e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sn', sa.Text(), nullable=False),
    sa.Column('is_alive_vcfront', sa.Boolean(), nullable=True),
    sa.Column('is_active_agent', sa.Boolean(), nullable=True),
    sa.Column('is_online_agent', sa.Boolean(), nullable=True),
    sa.Column('is_active_vuf', sa.Boolean(), nullable=True),
    sa.Column('account_email', sa.Text(), nullable=True),
    sa.Column('account_env', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_camera_statuses_sn', 'camera_statuses', ['sn'], unique=False)
    op.create_table('camera_transfer_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sn', sa.Text(), nullable=False),
    sa.Column('from_account_id', sa.Integer(), nullable=True),
    sa.Column('to_account_id', sa.Integer(), nullable=True),
    sa.Column('target_env', sa.Text(), nullable=True),
    sa.Column('task_status', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_camera_transfer_tasks_sn', 'camera_transfer_tasks', ['sn'], unique=False)
    op.create_table('last_mrs',
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('mr_iid', sa.Integer(), nullable=False),
    sa.Column('current_status', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('project_id', 'mr_iid')
    )
    op.create_table('project_pipelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline_id')
    )
    op.create_index('idx_project_pipelines_project_id', 'project_pipelines', ['project_id'], unique=False)
    op.create_table('schema_migrations',
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.Text(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('thread_message_id', sa.BigInteger(), nullable=True),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_notification', 'subscribers', ['project_id', 'notification_type'], unique=False)
    op.create_index('idx_user_project', 'subscribers', ['user_id', 'project_id'], unique=False)
    op.create_index('unique_subscription_group_thread_idx', 'subscribers', ['project_id', 'notification_type', sa.literal_column('COALESCE(chat_id, 0)'), sa.literal_column('COALESCE(thread_message_id, 0)'), 'source_type'], unique=True, postgresql_where=sa.text("source_type IN ('group', 'group_thread')"))
    op.create_index('unique_subscription_private_idx', 'subscribers', ['user_id', 'project_id', 'notification_type', sa.literal_column('COALESCE(chat_id, 0)'), sa.literal_column('COALESCE(thread_message_id, 0)'), 'source_type'], unique=True, postgresql_where=sa.text("source_type = 'private'"))
    op.create_table('white_list',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('white_list')
    op.drop_index('unique_subscription_private_idx', table_name='subscribers', postgresql_where=sa.text("source_type = 'private'"))
    op.drop_index('unique_subscription_group_thread_idx', table_name='subscribers', postgresql_where=sa.text("source_type IN ('group', 'group_thread')"))
    op.drop_index('idx_user_project', table_name='subscribers')
    op.drop_index('idx_project_notification', table_name='subscribers')
    op.drop_table('subscribers')
    op.drop_table('schema_migrations')
    op.drop_index('idx_project_pipelines_project_id', table_name='project_pipelines')
    op.drop_table('project_pipelines')
    op.drop_table('last_mrs')
    op.drop_index('idx_camera_transfer_tasks_sn', table_name='camera_transfer_tasks')
    op.drop_table('camera_transfer_tasks')
    op.drop_index('idx_camera_statuses_sn', table_name='camera_statuses')
    op.drop_table('camera_statuses')
    # ### end Alembic commands ###
